### ISSUE TITLE
Missing inputs in `manifest.yml`

### ISSUE THREAD

**Issue by JGAntunes** [iamanishroy/netlify-plugin-js-obfuscator#1]
Seems like the plugin currently relies on `inputs` as a mean to provide extra config: https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L47

However these are not specified in the plugin `manifest.yml` - https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/main/manifest.yml - for reference see - https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#inputs

**Comment by iamanishroy** [comment]
issue fixed!
added inputs:-

```
inputs:
  - name: compact
    description: Compact code output on one line.
    default: false
  - name: numbersToExpressions
    description: Enables numbers conversion to expressions
    default: true
  - name: simplify
    description: Enables additional code obfuscation through simplification.
    default: true
  - name: shuffleStringArray
    description: Randomly shuffles the stringArray array items
    default: true
  - name: splitStrings
    description: Splits literal strings into chunks with length of splitStringsChunkLength option value
    default: true
```
